### ISSUE TITLE
Propose to add marsilea examples

### ISSUE THREAD

**Issue by Mr-Milk** [holtzy/The-Python-Graph-Gallery#376]
Hi, thanks for developing such a fantastic website. It helped me a lot when I started with Python visualization years ago. Now I'm deep in the field, I have developed a new package called [Marsilea](https://github.com/Marsilea-viz/marsilea) for declarative creation of composable visualization in Python. Are you interested in checking it out and considering adding some examples with Marsilea? This project is still in a relatively early phase. Any feedback is welcomed!

I also developed a package called [legendkit](https://github.com/Marsilea-viz/legendkit) that helps customize legend styles and placement in matplotlib. It is used within Marsilea to create and layout multiple legends.

Some examples created with Marsilea, but you can do much more than what's shown below:
![](https://marsilea.readthedocs.io/en/stable/_images/sphx_glr_plot_oil_well_001_2_00x.png)
![](https://marsilea.readthedocs.io/en/stable/_images/sphx_glr_plot_pbmc3k_001_2_00x.png)

**Comment by holtzy** [comment]
Hi!
Thanks so much for your submission.
The library looks pretty solid already, congrats!

I think it is a bit too early to add examples in the gallery for now, since your doc state that the API is still in beta and can change.

Can you please come back to me in a few months when you reach a more stable phase?

Thanks so much again!
