### ISSUE TITLE
Adding Plotnine graphs

### ISSUE THREAD

**Issue by votti** [holtzy/The-Python-Graph-Gallery#5]
Hi there, thanks for providing this useful resource!

Half a year ago I was really excited to find https://github.com/has2k1/plotnine , the first really usable ggplot2 implementation in Python. The implementation is so close to ggplot2 that one can even use the ggplot2 tutorials and manual almost 1:1.

The gallery provides many nice examples of the usage: https://plotnine.readthedocs.io/en/stable/gallery.html
Maybe it would be helpful to add these examples to the Python graph gallery?

**Comment by holtzy** [comment]
Hi votti, Thanks for this suggestion. I have to study this library more in depth, it looks very promising. Thanks!

**Comment by votti** [comment]
I just remembered that there is even another repository with plotnine examples:
https://github.com/has2k1/plotnine-examples/

**Comment by holtzy** [comment]
I'm reaching the end of the bandwidth I had to update the gallery and did not find time for the plotnine library, so I'm gonna close this old issue :(

**Comment by ivanistheone** [comment]
Two more usage tutorials for `plotnine` in case you ever want to revisit this topic:
- https://github.com/cmparlettpelleriti/CPSC392ParlettPelleriti/blob/master/InClass/LectureNotebooks/Visualization%20I--Class%204.ipynb
- https://github.com/cmparlettpelleriti/CPSC392ParlettPelleriti/blob/master/InClass/LectureNotebooks/Visualization%20II--Class%205.ipynb

I'd be interested to contribute `plotnine` impl. of certain basic figures if there is interest (as measured by the number of thumbs up on this comment).

**Comment by holtzy** [comment]
Hi @ivanistheone, thanks for your comment.

As stated before, I would be very keen to add some plotnine examples to the gallery. I just don't have the bandwidth for it yet.

If you feel like contributing (that would be awesome! 😄 ), it would be cool to have a translation of any of the R graph gallery ggplot2 blogpost in plotnine.

Example: [density chart](https://www.r-graph-gallery.com/135-stacked-density-graph.html), [histogram](https://www.r-graph-gallery.com/220-basic-ggplot2-histogram.html) and so many others..

Otherwise I keep it in mind for when I will have more time on the project!

**Comment by ivanistheone** [comment]
### Is there a contributing guide somewhere?

I'm slowly getting around to looking at plotnine (I'm a beginner, but there are so many examples and this project has nice tooling so I want to try adding some basic charts just to get some practice with it).

I was looking to start with a boxplot, and I see each thumbnail is a [link to a notebook](https://github.com/holtzy/The-Python-Graph-Gallery/blob/master/src/pages/boxplot.js#L98-L102):

```JavaScript
          <ChartImageContainer
            imgName="33_Custom_Boxplot_color_Seaborn5"
            caption="Everything you need concerning color customization on your boxplot: transparency, palette in use, manual control.."
            linkTo="/33-control-colors-of-boxplot-seaborn"
          />
```

where the image is in [static/graph folder](https://github.com/holtzy/The-Python-Graph-Gallery/tree/master/static/graph) and the linkTo is [this notebook](https://github.com/holtzy/The-Python-Graph-Gallery/blob/master/src/notebooks/33-control-colors-of-boxplot-seaborn.ipynb), but **Q1**: how was the image name `33_Custom_Boxplot_color_Seaborn5.png` generated?

I'm guessing the `5` is an auto-incrementing, i.e. fifth graphic in the notebook, but where did `33_Custom_Boxplot_color_Seaborn` come from?

The notebook has  `slug = 33-control-colors-of-boxplot-seaborn` in the [metadata section](https://raw.githubusercontent.com/holtzy/The-Python-Graph-Gallery/master/src/notebooks/33-control-colors-of-boxplot-seaborn.ipynb) at the end of the .ipynb json, so that doesn't seem to be it.

**Q2**: Is there a build system for the notebooks that extracts all the graphics and put them into `static/graph`?

Any pointers and tips for getting started will be much appreciated.

**Comment by holtzy** [comment]
Hi @ivanistheone @votti 

I'm back with bandwidth to work on the gallery.

- I took another look at plotnine and it definitely makes sense to add examples to the gallery.

- I am currently documenting the process to add new examples in the repo [Wiki](https://github.com/holtzy/The-Python-Graph-Gallery/wiki)

- Q1 -> The images you see in the gallery are hand-made.
- Q2 -> NO, I do it by hand

Thanks!

**Comment by holtzy** [comment]
Closing now as we're in the process of adding examples with @JosephBARBIERDARNAL
